rescue_mission/config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers
  end

  resources :answers, only: [:show, :update]
end

rescue_mission/app/models/answer.rb
class Answer < ApplicationRecord
  validates :title, presence: true, length: { minimum: 15 }
  validates :body, presence: true, length: { minimum: 50 }
  validates :username, presence: true

  belongs_to :question
end

rescue_mission/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rescue_mission/app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { minimum: 40 }
  validates :body, presence: true, length: { minimum: 150 }
  validates :username, presence: true

  has_many :answers, dependent: :destroy
end

rescue_mission/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # before_action :set_answer, only: [:new]

  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.question = @question
    if @answer.save
      redirect_to @question, notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    @answer = Answer.find(params[:id])
    binding.pry
    if @answer.update_attributes(answer_params)
      redirect_to question_path(@answer.question), notice: 'Answer was successfully updated.'
    else
      redirect_to question_path(@answer.question), notice: 'Answer failed to update.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def answer_params
    params.require(:answer).permit(:title, :body, :username, :chosen)
  end
end

rescue_mission/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rescue_mission/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def show
    @answers = @question.answers.order(updated_at: :asc)
    @chosen_answer = @answers.find { |answer| answer.chosen == true }
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    @html_string = @markdown.render(@question.body)
  end

  def new
    @question = Question.new
  end

  def edit
    @queston = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def question_params
    params.require(:question).permit(:title, :body, :username)
  end
end

rescue_mission/app/helpers/application_helper.rb
module ApplicationHelper
end

rescue_mission/app/views/answers/_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>:
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>:
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :username %>:
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rescue_mission/app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', questions_path %>

rescue_mission/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rescue_mission/app/views/questions/_chosen.html.erb
<%= form_for(answer) do |f| %>
  <%= f.hidden_field(:chosen, :value => !answer.chosen) %>
  <%= f.submit "Best Answer" %>
  Chosen Value: <%= answer.chosen %>
<% end %>

rescue_mission/app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>:
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>:
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rescue_mission/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> | 
<%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', questions_path %>

rescue_mission/app/views/questions/index.html.erb
<h1>Questions</h1>

<ol>
  <% @questions.each do |question| %>
  <li>
    <strong><%= question.title %></strong>
    <%= link_to 'Details', question %>
    (<%= question.updated_at %>)
  </li>
  <% end %>
</ol>

<%= link_to 'Post a New Question', new_question_path %>

rescue_mission/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

rescue_mission/app/views/questions/show.erb
<p>
  <strong>Question:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @question.body %>
</p>
<p>
  <strong>Posted by:</strong>
  <%= @question.username %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

rescue_mission/app/views/questions/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @html_string.html_safe %>
</p>
<p>
  <strong>Posted by:</strong>
  <%= @question.username %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', questions_path %>

<br/>
<br/>
<%= link_to 'Post an Answer', new_question_answer_path(@question) %>
<br/>
<h2>Answers</h2>

<ol>
  <li>
    <strong><%= @chosen_answer.title %></strong> | <strong>Posted by:</strong>
    <%= @chosen_answer.username %> | (<%= @chosen_answer.updated_at %>)
    <br/><%= @markdown.render(@chosen_answer.body).html_safe %>
    <%= form_for(@chosen_answer) do |f| %>
        <%= f.hidden_field(:chosen, :value => !@chosen_answer.chosen) %>
        <%= f.submit "Best Answer" %>
        Chosen Value: <%= @chosen_answer.chosen %>
    <% end %>
  </li>
  <br/>
  <% @answers.each do |answer| %>
  <li>
    <strong><%= answer.title %></strong> | <strong>Posted by:</strong>
    <%= answer.username %> | (<%= answer.updated_at %>)
    <br/><%= @markdown.render(answer.body).html_safe %>
    <%= form_for(answer) do |f| %><%= f.hidden_field(:chosen, :value => !answer.chosen) %><%= f.submit "Best Answer" %>
      Chosen Value: <%= answer.chosen %>
    <% end %>
    <br/>
  </li>
  <% end %>
</ol>
<br/>
<%= link_to 'Back', questions_path %>